### ISSUE TITLE
"invalid poly" and "poly in wrong detection" in training

### ISSUE THREAD

**Issue by 595972434** [HaozhengLi/EAST_ICPR#3]
Hello 
      I have got a normal trainingset by using transform.m ,however there was some "invalid poly" and "poly in wrong detection" in training.Is this normal？How should i correct this error？ @HaozhengLi 
![screenshot from 2018-05-16 10 44 55](https://user-images.githubusercontent.com/27463961/40093778-48982084-58f6-11e8-9d3c-388c0d6aa759.png)

**Comment by HaozhengLi** [comment]
hello @595972434 

If you imshow your data transformed in matlab, you will find all of them are actually normal.

1. As for the 'invalid poly' errors, this is because some of your origin images are too small.
For more details, please see <[Data-set formating and small area of polygon #79](https://github.com/argman/EAST/issues/79)>.

2. As for the 'poly in wrong detection' errors, many other people find that no matter how you pre-process the images, some little 'poly in wrong detection' errors will still occor.
For more details, please see <[Poly in wrong direction during training on the Cursive Text (Written from right to left) #104](https://github.com/argman/EAST/issues/104)>.

So don't worry.

After you have run <[transform.m](https://github.com/HaozhengLi/EAST_ICPR/blob/master/data_transform/transform.m)> to pre-process [ICPR2018](https://tianchi.aliyun.com/competition/information.htm?spm=5176.100067.5678.2.2ba06a80jtSrlf&raceId=231651), please just continue training.
